version: '3.7'

services:
  proxy:
    image: traefik:2.1.4
    restart: always
    ports:
      - '80:80'
      - '8080:8080' # dashboard
    command:
      # api settings
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      # provider settings
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=ntrs-react-web
      # entrypoints
      - --entrypoints.web.address=:80 # <===> defining entrypoint for http on port 80 named web
    # - --entrypoints.web-secured.address=:443 <===> defining entrypoint for https on port 443 named web-secured
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ntrs-react-web
    #labels:
    # define the rules of the traefik proxy for this container
    # - 'traefik.enable=true'
    # - 'traefik.http.routers.api.rule=Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
    # - 'traefik.http.routers.api.service=api@internal'
  web-server:
    build:
      context: ./web-server
      target: dev
    networks:
      - ntrs-react-web
    ports:
      - '9229:9229'
    environment:
      - MONGO_USER
      - MONGO_HOST
      - MONGO_PASSWORD
      - ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET
      - NODE_ENV
    env_file: ./web-server/config.env
    volumes:
      - /opt/node_app/node_modules
      - ./web-server/:/opt/node_app/
    labels:
      # define the rules of the traefik proxy for this container
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend-server.rule=Host(`server.localhost`) && (PathPrefix(`/api`))'
      - 'traefik.http.routers.backend-server.entrypoints=web'
      - 'traefik.http.routers.backend-server.service=web-server-natours'
      - 'traefik.http.services.web-server-natours.loadbalancer.server.scheme=http'
      - 'traefik.http.services.web-server-natours.loadbalancer.server.port=4000'

networks:
  ntrs-react-web:
    external: false
